debug: false
#uuid: null
#token_id: null
#token: null
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: ""
    key: ""
  upload_limit: 100
system:
  data: /var/lib/pelican/volumes
  sftp:
    bind_port: 2022
remote: "https://pp.holocons.xyz"
allowed_mounts: []
ignore_panel_config_updates: true
