services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    container_name: panel
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - data:/pelican-data/
      - logs:/var/www/html/storage/logs/
    environment:
      XDG_DATA_HOME: /pelican-data
      APP_URL: "https://pp.holocons.xyz"
      ADMIN_EMAIL: "gator@holocons.xyz"
      BEHIND_PROXY: "true"
      TRUSTED_PROXIES: "private_ranges"
    networks:
      - default_nw
    extra_hosts:
      - "host.docker.internal=host-gateway"
    restart: always
networks:
  default_nw:
    external: true
volumes:
  data: null
  logs: null
